Repository openvinotoolkit/datumaro, pull requests merged in 2023-03, with the labels that each got.

#828 Develop DatumaroBinaryFormat to export/import the dataset header & DatasetItem
  .github/workflows/pr_check.yml
  datumaro/components/media.py
  datumaro/plugins/data_formats/datumaro/base.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/base.py
  datumaro/plugins/data_formats/datumaro_binary/crypter.py
  datumaro/plugins/data_formats/datumaro_binary/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/format.py
  datumaro/plugins/data_formats/datumaro_binary/importer.py
  datumaro/plugins/data_formats/datumaro_binary/mapper.py
  requirements-core.txt
  setup.py
  tests/unit/data_formats/datumaro/conftest.py
  tests/unit/data_formats/datumaro/test_datumaro_binary_format.py
  tests/unit/data_formats/datumaro/test_datumaro_format.py
Labels: enhancement, data formats

#829 Implement DatumaroBinaryFormat to export/import the image dataset completely
  datumaro/components/annotation.py
  datumaro/components/format_detection.py
  datumaro/components/media.py
  datumaro/components/operations.py
  datumaro/plugins/data_formats/datumaro_binary/__init__.py
  datumaro/plugins/data_formats/datumaro_binary/base.py
  datumaro/plugins/data_formats/datumaro_binary/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/importer.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/__init__.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/annotation.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/common.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/dataset_item.py
  datumaro/plugins/data_formats/mvtec/exporter.py
  datumaro/util/__init__.py
  tests/unit/data_formats/datumaro/conftest.py
  tests/unit/data_formats/datumaro/test_datumaro_binary_format.py
  tests/unit/test_ops.py
Labels: enhancement, data formats

#835 Fix bugs in mvtec exporter
  CHANGELOG.md
  datumaro/plugins/data_formats/mvtec/exporter.py
  tests/unit/test_mvtec_format.py
Labels: bug, data formats

#838 [Doc] Add documentation for searcher cli
  CHANGELOG.md
  site/content/en/docs/user-manual/command-reference/searcher.md
Labels: documentation

#836 Fix CIFAR10 and 100 detect function
  CHANGELOG.md
  datumaro/plugins/data_formats/cifar.py
  tests/unit/test_cifar_format.py
Labels: bug, data formats

#832 [Doc] Add some description
  site/content/en/docs/python-api/_index.md
  site/content/en/docs/python-api/python-api-examples/_index.md
Labels: documentation

#839 Choose the top priority detect format for all directory depths
  CHANGELOG.md
  datumaro/components/environment.py
  datumaro/components/format_detection.py
  tests/unit/test_format_detection.py
Labels: bug, data formats

#847 Add AVA action data format support
  CHANGELOG.md
  datumaro/plugins/data_formats/ava/__init__.py
  datumaro/plugins/data_formats/ava/ava.py
  datumaro/plugins/data_formats/ava/ava_label.proto
  datumaro/plugins/data_formats/ava/ava_label_pb2.py
  datumaro/plugins/data_formats/video.py
  tests/assets/ava_dataset/annotations/ava_action_list_v2.2.pbtxt
  tests/assets/ava_dataset/annotations/ava_default_v2.2.csv
  tests/assets/ava_dataset/frames/video0/video0_000000.jpg
  tests/assets/ava_dataset/frames/video0/video0_000001.jpg
  tests/assets/ava_dataset/frames/video1/video1_000000.jpg
  tests/assets/ava_dataset/frames/video1/video1_000001.jpg
  tests/unit/test_ava_format.py
Labels: enhancement, data formats

#843 Fix MVTec format detect function
  CHANGELOG.md
  datumaro/plugins/data_formats/mvtec/importer.py
  tests/unit/test_mvtec_format.py
Labels: bug, data formats

#854 Fix wrong __len__() of Subset when the item is removed
  CHANGELOG.md
  datumaro/components/dataset.py
  tests/unit/test_dataset.py
Labels: bug

#837 Fix celeba and align_celeba detect function
  CHANGELOG.md
  datumaro/cli/util/project.py
  datumaro/plugins/data_formats/celeba/__init__.py
  datumaro/plugins/data_formats/celeba/align_celeba.py
  datumaro/plugins/data_formats/celeba/celeba.py
  datumaro/plugins/data_formats/image_dir.py
  tests/unit/test_align_celeba_format.py
Labels: bug, data formats

#860 Fix mask visualization bug
  datumaro/components/visualizer.py
Labels: bug

#856 Add YOLO Loose format
  CHANGELOG.md
  datumaro/components/dataset_base.py
  datumaro/components/format_detection.py
  datumaro/components/importer.py
  datumaro/components/media.py
  datumaro/plugins/data_formats/yolo/base.py
  datumaro/plugins/data_formats/yolo/format.py
  datumaro/plugins/data_formats/yolo/importer.py
  datumaro/util/definitions.py
  datumaro/util/os_util.py
  notebooks/06_tiling.ipynb
  site/content/en/docs/formats/yolo.md
  tests/assets/yolo_dataset/annotations/Annotations/1.txt
  tests/assets/yolo_dataset/annotations/Images/1.jpg
  tests/assets/yolo_dataset/annotations/obj.names
  tests/assets/yolo_dataset/labels/README.txt
  tests/assets/yolo_dataset/labels/images/train/1.jpg
  tests/assets/yolo_dataset/labels/images/val/1.jpg
  tests/assets/yolo_dataset/labels/labels/train/1.txt
  tests/assets/yolo_dataset/labels/labels/val/1.txt
  tests/assets/yolo_dataset/labels/obj.names
  tests/assets/yolo_dataset/strict/obj.data
  tests/assets/yolo_dataset/strict/obj.names
  tests/assets/yolo_dataset/strict/obj_train_data/1.jpg
  tests/assets/yolo_dataset/strict/obj_train_data/1.txt
  tests/assets/yolo_dataset/strict/train.txt
  tests/unit/data_formats/base.py
  tests/unit/data_formats/test_common_semantic_segmentation_format.py
  tests/unit/data_formats/test_yolo_format.py
  tests/unit/test_yolo_format.py
Labels: enhancement, data formats

#859 Add Ultralytics YOLO format
  CHANGELOG.md
  datumaro/plugins/data_formats/yolo/base.py
  datumaro/plugins/data_formats/yolo/exporter.py
  datumaro/plugins/data_formats/yolo/format.py
  datumaro/plugins/data_formats/yolo/importer.py
  notebooks/08_e2e_example_yolo_ultralytics_trainer.ipynb
  site/content/en/docs/formats/yolo_ultralytics.md
  site/content/en/docs/python-api/python-api-examples/e2e_example_yolo_ultralytics_trainer.md
  site/content/en/docs/user-manual/command-reference/projects.md
  site/content/en/docs/user-manual/supported_formats.md
  tests/unit/data_formats/datumaro/test_datumaro_binary_format.py
  tests/unit/data_formats/test_yolo_format.py
Labels: enhancement, data formats

#869 Update PR template
  .github/pull_request_template.md
Labels: CI, RELEASE

#874 Update doc for regex rules in transform
  datumaro/plugins/transforms.py
  site/content/en/docs/user-manual/command-reference/transform.md
Labels: DOC, RELEASE

#867 Add publish to PyPI Github action
  .github/workflows/pypi_publish.yml
  .gitignore
  CHANGELOG.md
Labels: CI

#872 Add Video formats (video_frames and video_keyframes)
  site/content/en/docs/formats/video.md
Labels: DOC, RELEASE

#878 Add prefix to secret key
  datumaro/components/crypter.py
  datumaro/plugins/data_formats/datumaro_binary/crypter.py
Labels: FIX, RELEASE

#877 Add missing requirements
  requirements-core.txt
Labels: FIX, RELEASE

#875 Add --no-media-encryption option
  CHANGELOG.md
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/base.py
  datumaro/plugins/data_formats/datumaro_binary/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/format.py
  tests/integration/cli/test_dm_binary_encryption.py
  tests/unit/data_formats/datumaro/test_datumaro_binary_format.py
Labels: ENHANCE, RELEASE

#884 Update 3rd-party.txt
  3rd-party.txt
Labels: RELEASE

#880 Add datumaro binary format documentation
  CHANGELOG.md
  datumaro/plugins/data_formats/datumaro_binary/exporter.py
  notebooks/09_encrypt_dataset.ipynb
  site/content/en/docs/formats/datumaro.md
  site/content/en/docs/formats/datumaro_binary.md
  site/content/en/docs/python-api/python-api-examples/e2e_example_yolo_ultralytics_trainer.md
  site/content/en/docs/python-api/python-api-examples/encrypt_dataset.md
Labels: DOC, RELEASE

#886 Version up to Releases/1.1.0
  CHANGELOG.md
  datumaro/version.py
Labels: RELEASE

#890 Fix lint error for precommit
  .github/workflows/linter.yml
  .pre-commit-config.yaml
  MANIFEST.in
  datumaro/components/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/mapper.py
  datumaro/plugins/data_formats/open_images.py
  datumaro/plugins/openvino_plugin/samples/coco.class
  datumaro/plugins/openvino_plugin/samples/imagenet.class
  datumaro/plugins/synthetic_data/background_colors.txt
  dev/requirements.txt
  requirements-dev.txt
  requirements.txt
  tests/requirements-linters.txt
  tests/requirements.txt
Labels: CI

#891 Add UserWarning if an invalid media_type comes to image statistics computation
  CHANGELOG.md
  datumaro/components/operations.py
  tests/requirements.py
  tests/unit/operations/__init__.py
  tests/unit/operations/test_statistics.py
  tests/unit/test_ops.py
Labels: BUG

#896 Fix to not export absolute media path in Datumaro and DatumaroBinary formats
  CHANGELOG.md
  datumaro/components/exporter.py
  datumaro/plugins/data_formats/datumaro/base.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/base.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/dataset_item.py
  datumaro/plugins/data_formats/datumaro_binary/mapper/media.py
  tests/unit/data_formats/datumaro/test_datumaro_format.py
  tests/utils/test_utils.py
Labels: BUG

#895 Change pypi_publish.yml to publish_sdist_to_pypi.yml
  .github/workflows/publish_sdist_to_pypi.yml
  .github/workflows/pypi_publish.yml
Labels: CI

#903 Add notification to Teams channel for cron jobs on failure
  .github/workflows/code_scan.yml
  .github/workflows/nightly_check.yml
  .github/workflows/weekly_check.yml
Labels: CI

#900 Rename version variable
  datumaro/__init__.py
  datumaro/cli/__main__.py
  datumaro/plugins/data_formats/datumaro/base.py
  datumaro/version.py
  setup.py
  site/source/conf.py
Labels: user experience

#901 Refactor operations
  .pre-commit-config.yaml
  CHANGELOG.md
  datumaro/components/annotations/__init__.py
  datumaro/components/annotations/matcher.py
  datumaro/components/annotations/merger.py
  datumaro/components/dataset.py
  datumaro/components/merge/__init__.py
  datumaro/components/merge/base.py
  datumaro/components/operations.py
Labels: refactoring

#906 Move merge policies to datumaro/components/merge directory
  CHANGELOG.md
  datumaro/cli/commands/merge.py
  datumaro/components/hl_ops.py
  datumaro/components/merge/__init__.py
  datumaro/components/merge/exact_merge.py
  datumaro/components/merge/intersect_merge.py
  datumaro/components/merge/union_merge.py
  datumaro/components/operations.py
  tests/unit/test_api.py
  tests/unit/test_dataset.py
  tests/unit/test_ops.py
Labels: refactoring

#902 Add CODEOWNERS and auto issue assignment
  .github/CODEOWNERS
  .github/workflows/issue_assignment.yml
Labels: CI
