Repository openvinotoolkit/datumaro, pull requests merged in 2023-08, with the labels that each got.

#1115 Remove xfail marks from the convert integration tests
  CHANGELOG.md
  src/datumaro/plugins/data_formats/datumaro/base.py
  tests/integration/cli/test_convert.py
  tests/utils/test_utils.py
Labels: ENHANCE

#1116 Enhance ClassificationValidator to cope with multilabel classification datasets with label_groups
  CHANGELOG.md
  src/datumaro/components/annotation.py
  src/datumaro/plugins/data_formats/datumaro/base.py
  src/datumaro/plugins/data_formats/datumaro/exporter.py
  src/datumaro/plugins/validators.py
  tests/assets/datumaro_dataset/legacy/annotations/test.json
  tests/assets/datumaro_dataset/legacy/annotations/train.json
  tests/assets/datumaro_dataset/legacy/annotations/validation.json
  tests/unit/test_labeling.py
  tests/unit/test_validator.py
Labels: ENHANCE

#1120 Add Rust API to optimize COCOPageMapper performance
  .github/workflows/health_check.yml
  .github/workflows/nightly_check.yml
  .github/workflows/pr_check.yml
  .gitignore
  CHANGELOG.md
  MANIFEST.in
  contributing.md
  pyproject.toml
  rust/Cargo.toml
  rust/src/coco_page_mapper.rs
  rust/src/lib.rs
  rust/src/page_maps.rs
  rust/src/utils.rs
  setup.py
  src/datumaro/plugins/data_formats/coco/page_mapper.py
Labels: FEATURE

#1121 add ellipse to 'ShapesToBoxes' transform
  src/datumaro/plugins/transforms.py
  tests/unit/test_transforms.py
Labels: ENHANCE

#1123 Fix bugs for Tile transform
  CHANGELOG.md
  src/datumaro/components/media.py
  src/datumaro/plugins/tiling/tile.py
  tests/unit/test_images.py
Labels: BUG

#1124 support video annotation
  CHANGELOG.md
  docs/source/docs/data-formats/datumaro_format.md
  docs/source/docs/data-formats/formats/datumaro.md
  docs/source/docs/data-formats/formats/datumaro_binary.md
  src/datumaro/components/annotation.py
  src/datumaro/components/exporter.py
  src/datumaro/components/media.py
  src/datumaro/plugins/data_formats/arrow/exporter.py
  src/datumaro/plugins/data_formats/datumaro/base.py
  src/datumaro/plugins/data_formats/datumaro/exporter.py
  src/datumaro/plugins/data_formats/datumaro/format.py
  src/datumaro/plugins/data_formats/datumaro_binary/base.py
  src/datumaro/plugins/data_formats/datumaro_binary/exporter.py
  src/datumaro/plugins/data_formats/datumaro_binary/format.py
  src/datumaro/plugins/data_formats/datumaro_binary/mapper/annotation.py
  src/datumaro/plugins/data_formats/datumaro_binary/mapper/media.py
  tests/integration/cli/test_video.py
  tests/unit/test_video.py
  tests/utils/test_utils.py
Labels: data formats

#1129 Add SAM OVMS and Triton server Docker image builders
  .github/codecov.yml
  CHANGELOG.md
  docker/segment-anything/Dockerfile.exporter
  docker/segment-anything/Dockerfile.ovms
  docker/segment-anything/Dockerfile.triton
  docker/segment-anything/README.md
  docker/segment-anything/build_ovms.sh
  docker/segment-anything/build_triton.sh
  docker/segment-anything/export_onnx_encoder.py
  docker/segment-anything/images/intel_rnb.jpg
  docker/segment-anything/ovms/model_config_list.json
  docker/segment-anything/test_model_servers.ipynb
  docker/segment-anything/triton/sam_decoder/config.pbtxt
  docker/segment-anything/triton/sam_encoder/config.pbtxt
Labels: FEATURE
