Repository openvinotoolkit/datumaro, pull requests merged in 2023-05, with the labels that each got.

#980 Fix project level CVAT for images format import
  CHANGELOG.md
  datumaro/plugins/data_formats/cvat/base.py
  tests/assets/cvat_dataset/for_video/images/frame_000016.png
  tests/unit/test_cvat_format.py
Labels: BUG, data formats

#985 Fix broken directory structure of Imagenet format
  docs/source/docs/explanation/formats/imagenet.md
Labels: DOC

#982 Fix an info message when using the convert CLI command with no args.input_format
  datumaro/cli/commands/convert.py
  tests/integration/cli/test_convert.py
  tests/utils/test_utils.py
Labels: BUG

#986 Fix media contents error in arrow format
  CHANGELOG.md
  datumaro/components/media.py
  datumaro/plugins/data_formats/arrow/mapper/media.py
  tests/unit/data_formats/arrow/test_arrow_format.py
  tests/unit/test_images.py
Labels: BUG

#981 Save and load hashkey for explorer
  CHANGELOG.md
  datumaro/cli/commands/explore.py
  datumaro/components/explorer.py
  datumaro/components/exporter.py
  datumaro/components/project.py
  datumaro/plugins/data_formats/datumaro/base.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/explorer.py
  datumaro/plugins/openvino_plugin/samples/clip_visual_ViT-B_32_interp.py
  datumaro/util/meta_file_util.py
  docs/source/docs/command-reference/context_free/explorer.md
  tests/integration/cli/test_explore.py
  tests/unit/test_explorer.py
Labels: ENHANCE

#995 Grant write permission to auto-issue-assigner
  .github/workflows/issue_assignment.yml
Labels: CI

#996 Add intermediate skill docs for filter
  CHANGELOG.md
  docs/source/docs/level-up/advanced_skills/12_project_versioning.rst
  docs/source/docs/level-up/advanced_skills/13_pseudo_label_generation.rst
  docs/source/docs/level-up/advanced_skills/index.rst
  docs/source/docs/level-up/intermediate_skills/09_data_filtering.rst
  docs/source/docs/level-up/intermediate_skills/10_data_exploration.rst
  docs/source/docs/level-up/intermediate_skills/11_data_generation.rst
  docs/source/docs/level-up/intermediate_skills/index.rst
Labels: DOC

#1000 Add COCO Roboflow section
  CHANGELOG.md
  docs/source/docs/data-formats/supported_formats.md
  docs/source/docs/explanation/formats/coco.md
Labels: DOC

#999 Add MOT and MOTS data format docs
  CHANGELOG.md
  docs/source/docs/data-formats/supported_formats.md
  docs/source/docs/explanation/formats/index.rst
  docs/source/docs/explanation/formats/mot.md
  docs/source/docs/explanation/formats/mots.md
Labels: DOC

#1001 Drop a malformed transform from StackedTransform automatically
  CHANGELOG.md
  datumaro/components/dataset.py
  tests/unit/test_dataset.py
Labels: BUG

#1005 Add Segment Anything data format
  CHANGELOG.md
  datumaro/components/format_detection.py
  datumaro/plugins/data_formats/segment_anything/__init__.py
  datumaro/plugins/data_formats/segment_anything/base.py
  datumaro/plugins/data_formats/segment_anything/exporter.py
  datumaro/plugins/data_formats/segment_anything/importer.py
  datumaro/util/annotation_util.py
  tests/assets/segment_anything_dataset/a.jpg
  tests/assets/segment_anything_dataset/a.json
  tests/assets/segment_anything_dataset/b.jpg
  tests/assets/segment_anything_dataset/b.json
  tests/unit/data_formats/test_segment_anything_format.py
Labels: data formats, FEATURE

#1006 Add Corrector transformation
  CHANGELOG.md
  datumaro/components/validator.py
  datumaro/plugins/transforms.py
  datumaro/plugins/validators.py
  notebooks/12_correct_dataset.ipynb
  tests/unit/algorithms/test_corrector.py
  tests/unit/test_validator.py
Labels: FEATURE

#1009 Add segment anything doc
  CHANGELOG.md
  docs/source/docs/data-formats/supported_formats.md
  docs/source/docs/explanation/formats/index.rst
  docs/source/docs/explanation/formats/segment_anything.md
Labels: DOC

#1008 Implement ReindexAnnotations transform
  CHANGELOG.md
  datumaro/plugins/transforms.py
  tests/unit/test_transforms.py
Labels: FEATURE

#1013 Refactor: change Exporter::apply() to Exporter::_apply_impl()
  datumaro/components/exporter.py
  datumaro/plugins/data_formats/arrow/exporter.py
  datumaro/plugins/data_formats/ava/ava.py
  datumaro/plugins/data_formats/camvid.py
  datumaro/plugins/data_formats/cifar.py
  datumaro/plugins/data_formats/cityscapes.py
  datumaro/plugins/data_formats/coco/exporter.py
  datumaro/plugins/data_formats/cvat/exporter.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/datumaro_binary/exporter.py
  datumaro/plugins/data_formats/icdar/exporter.py
  datumaro/plugins/data_formats/image_dir.py
  datumaro/plugins/data_formats/image_zip.py
  datumaro/plugins/data_formats/imagenet.py
  datumaro/plugins/data_formats/imagenet_txt.py
  datumaro/plugins/data_formats/kitti/exporter.py
  datumaro/plugins/data_formats/kitti_raw/exporter.py
  datumaro/plugins/data_formats/labelme.py
  datumaro/plugins/data_formats/lfw.py
  datumaro/plugins/data_formats/market1501.py
  datumaro/plugins/data_formats/mnist.py
  datumaro/plugins/data_formats/mnist_csv.py
  datumaro/plugins/data_formats/mot.py
  datumaro/plugins/data_formats/mots.py
  datumaro/plugins/data_formats/mvtec/exporter.py
  datumaro/plugins/data_formats/open_images.py
  datumaro/plugins/data_formats/segment_anything/exporter.py
  datumaro/plugins/data_formats/sly_pointcloud/exporter.py
  datumaro/plugins/data_formats/tf_detection_api/exporter.py
  datumaro/plugins/data_formats/vgg_face2.py
  datumaro/plugins/data_formats/voc/exporter.py
  datumaro/plugins/data_formats/widerface.py
  datumaro/plugins/data_formats/yolo/exporter.py
  tests/unit/test_dataset.py
Labels: refactoring

#1011 Add Jupyter notebook example of noisy label detection for detection tasks
  CHANGELOG.md
  datumaro/components/algorithms/noisy_label_detection/loss_dynamics_analyzer.py
  datumaro/components/visualizer.py
  docs/source/docs/jupyter_notebook_examples/e2e_example.rst
  notebooks/10_noisy_label_detection_cls.ipynb
  notebooks/13_noisy_label_detection_det.ipynb
  tests/assets/algorithms/noisy_label_detection_cls/annotations/train.json
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_0_1.jpg
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_0_2.jpg
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_0_3.jpg
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_1_1.jpg
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_1_2.jpg
  tests/assets/algorithms/noisy_label_detection_cls/images/train/label_1_3.jpg
  tests/assets/algorithms/noisy_label_detection_det/annotations/train.json
  tests/unit/algorithms/test_noisy_label_detection.py
Labels: DOC, ENHANCE

#1018 Update links and outdated contents in contributing.md
  README.md
  contributing.md
Labels: DOC

#1003 Support for format-agnostic storage and loading of hashkey
  CHANGELOG.md
  datumaro/cli/commands/explore.py
  datumaro/components/annotation.py
  datumaro/components/dataset.py
  datumaro/components/exporter.py
  datumaro/plugins/data_formats/cifar.py
  datumaro/plugins/data_formats/datumaro/base.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/vgg_face2.py
  datumaro/util/meta_file_util.py
  docs/source/docs/level-up/intermediate_skills/10_data_exploration.rst
  tests/unit/test_annotation.py
  tests/unit/test_hashkey.py
Labels: ENHANCE

#1024 Constraint cityscapes dataset structure
  datumaro/plugins/data_formats/cityscapes.py
Labels: ENHANCE

#1025 Update 02_merge_detection_data notebook with real datasets
  notebooks/02_merge_heterogeneous_datasets_for_detection.ipynb
Labels: DOC

#1023 Add notebook for importing/exporting segmentation data
  CHANGELOG.md
  datumaro/plugins/data_formats/cityscapes.py
  docs/source/docs/data-formats/formats/cityscapes.md
  docs/source/docs/data-formats/formats/index.rst
  docs/source/docs/jupyter_notebook_examples/dataset_IO.rst
  notebooks/14_import_export_det_data.ipynb
  notebooks/15_import_export_seg_data.ipynb
  tests/assets/cityscapes_dataset/dataset/leftImg8bit/test/defaultcity/defaultcity_000001_000031_leftImg8bit.png
  tests/assets/cityscapes_dataset/dataset/leftImg8bit/test/defaultcity/defaultcity_000001_000032_leftImg8bit.png
  tests/assets/cityscapes_dataset/dataset/leftImg8bit/train/defaultcity/defaultcity_000002_000045_leftImg8bit.png
  tests/assets/cityscapes_dataset/dataset/leftImg8bit/val/defaultcity/defaultcity_000001_000019_leftImg8bit.png
  tests/assets/cityscapes_dataset/train_dataset/leftImg8bit/test/defaultcity/defaultcity_000001_000031_leftImg8bit.png
  tests/assets/cityscapes_dataset/train_dataset/leftImg8bit/test/defaultcity/defaultcity_000001_000032_leftImg8bit.png
  tests/assets/cityscapes_dataset/train_dataset/leftImg8bit/train/defaultcity/defaultcity_000002_000045_leftImg8bit.png
  tests/assets/cityscapes_dataset/train_dataset/leftImg8bit/val/defaultcity/defaultcity_000001_000019_leftImg8bit.png
  tests/unit/test_cityscapes_format.py
Labels: BUG, DOC

#1029 Fix cityscapes detection error
  datumaro/plugins/data_formats/cityscapes.py
Labels: BUG
