Repository openvinotoolkit/datumaro, pull requests merged in 2023-06, with the labels that each got.

#1031 Enhance import performance for built-in plugins
  CHANGELOG.md
  MANIFEST.in
  contributing.md
  datumaro/cli/commands/convert.py
  datumaro/cli/commands/detect_format.py
  datumaro/cli/commands/download.py
  datumaro/cli/commands/merge.py
  datumaro/cli/commands/patch.py
  datumaro/cli/commands/require_project/modification/add.py
  datumaro/cli/commands/require_project/modification/export.py
  datumaro/cli/commands/require_project/modification/import_.py
  datumaro/cli/commands/transform.py
  datumaro/cli/commands/validate.py
  datumaro/components/dataset.py
  datumaro/components/environment.py
  datumaro/components/lazy_plugin.py
  datumaro/plugins/README.md
  datumaro/plugins/accuracy_checker_plugin/ac_launcher.py
  datumaro/plugins/data_formats/tf_detection_api/base.py
  datumaro/plugins/data_formats/tf_detection_api/exporter.py
  datumaro/plugins/specs.json
  datumaro/plugins/specs.py
  requirements-default.txt
  tests/unit/test_dataset.py
  tests/unit/test_environment.py
  tests/unit/test_validator.py
Labels: ENHANCE

#1036 Upgrade OpenVINO version to 2023.0.0
  CHANGELOG.md
  requirements-core.txt
  requirements-default.txt
Labels: dependencies

#1012 CLI update from diff to compare & add TableComparator
  CHANGELOG.md
  docs/source/docs/command-reference/context_free/compare.md
  docs/source/docs/explanation/command_line.dot
  docs/source/docs/explanation/project.rst
  docs/source/docs/get-started/quick-start-guide/examples.rst
  src/datumaro/cli/commands/__init__.py
  src/datumaro/cli/commands/compare.py
  src/datumaro/cli/util/compare.py
  src/datumaro/components/comparator.py
  src/datumaro/components/hl_ops/__init__.py
  src/datumaro/components/operations.py
  src/datumaro/components/shift_analyzer.py
  src/datumaro/plugins/openvino_plugin/shift_launcher.py
  src/datumaro/plugins/specs.json
  src/datumaro/util/telemetry_utils.py
  tests/integration/cli/test_compare.py
  tests/unit/test_api.py
  tests/unit/test_compare.py
Labels: refactoring, FEATURE

#1039 Fix warnings in test_visualizer.py
  CHANGELOG.md
  tests/unit/test_visualizer.py
Labels: BUG

#1041 Change default dtype of load_image() to np.uint8
  CHANGELOG.md
  src/datumaro/util/image.py
Labels: ENHANCE

#1043 Fix label_groups typing
  src/datumaro/components/annotation.py
Labels: BUG

#1045 Make specs.json more interpretable
  src/datumaro/components/environment.py
  src/datumaro/plugins/sampler/algorithm/__init__.py
  src/datumaro/plugins/specs.json
  src/datumaro/plugins/specs.py
  tests/unit/test_environment.py
Labels: BUG, ENHANCE

#1048 Install dvc version to 2.x
  requirements-default.txt
Labels: CI

#1046 Update to the latest OpenVINO API
  src/datumaro/components/shift_analyzer.py
  src/datumaro/plugins/explorer.py
  src/datumaro/plugins/openvino_plugin/launcher.py
  src/datumaro/plugins/openvino_plugin/samples/googlenet-v4-tf_interp.py
  src/datumaro/plugins/openvino_plugin/shift_launcher.py
  tests/assets/rise/model_interp.py
  tests/unit/test_shift_analyzer.py
Labels: BUG

#1050 Hotfix to release 1.3.2
  CHANGELOG.md
  datumaro/plugins/data_formats/coco/base.py
  datumaro/plugins/validators.py
  datumaro/version.py
  docs/source/docs/release_notes.rst
  requirements-default.txt
  tests/unit/test_coco_format.py
Labels: BUG, ENHANCE

#1054 Prevent installing protobuf>=4
  CHANGELOG.md
  requirements-core.txt
  setup.py
  tests/requirements.txt
  tests/unit/test_extractor_tfds.py
  tox.ini
Labels: BUG

#1047 Add OTX ATSS detector model interpreter & refactor interfaces
  CHANGELOG.md
  src/datumaro/components/abstracts/__init__.py
  src/datumaro/components/abstracts/merger.py
  src/datumaro/components/abstracts/model_interpreter.py
  src/datumaro/components/annotations/matcher.py
  src/datumaro/components/comparator.py
  src/datumaro/components/merge/base.py
  src/datumaro/components/merge/intersect_merge.py
  src/datumaro/plugins/openvino_plugin/launcher.py
  src/datumaro/plugins/openvino_plugin/samples/clip_text_ViT-B_32_interp.py
  src/datumaro/plugins/openvino_plugin/samples/clip_visual_ViT-B_32_interp.py
  src/datumaro/plugins/openvino_plugin/samples/googlenet-v4-tf_interp.py
  src/datumaro/plugins/openvino_plugin/samples/mobilenet_v2_pytorch_interp.py
  src/datumaro/plugins/openvino_plugin/samples/otx_custom_object_detection_gen3_atss_interp.py
  src/datumaro/plugins/openvino_plugin/samples/ssd_face_detection_interp.py
  src/datumaro/plugins/openvino_plugin/samples/ssd_mobilenet_coco_detection_interp.py
  src/datumaro/plugins/openvino_plugin/samples/ssd_person_detection_interp.py
  src/datumaro/plugins/openvino_plugin/samples/ssd_person_vehicle_bike_detection_interp.py
  src/datumaro/plugins/openvino_plugin/samples/ssd_vehicle_detection_interp.py
  tests/assets/rise/model_interp.py
  tests/unit/test_openvino_launcher.py
Labels: FEATURE

#1053 Fix LabelMe data format
  src/datumaro/plugins/data_formats/labelme.py
  tests/assets/labelme_dataset/Annotations/subset1/img1.xml
  tests/assets/labelme_dataset/Images/subset1/img1.png
  tests/assets/labelme_dataset/Masks/subset1/img1_mask_1.png
  tests/assets/labelme_dataset/Masks/subset1/img1_mask_5.png
  tests/assets/labelme_dataset/Scribbles/subset1/img1_scribble_1.png
  tests/assets/labelme_dataset/Scribbles/subset1/img1_scribble_5.png
  tests/assets/labelme_dataset/img1.xml
  tests/unit/test_labelme_format.py
Labels: BUG, data formats

#1044 Add Roboflow data formats
  CHANGELOG.md
  src/datumaro/plugins/data_formats/coco/importer.py
  src/datumaro/plugins/data_formats/roboflow/__init__.py
  src/datumaro/plugins/data_formats/roboflow/base.py
  src/datumaro/plugins/data_formats/roboflow/importer.py
  src/datumaro/plugins/data_formats/tf_detection_api/base.py
  src/datumaro/plugins/data_formats/tf_detection_api/format.py
  src/datumaro/plugins/data_formats/voc/base.py
  src/datumaro/plugins/data_formats/voc/format.py
  src/datumaro/plugins/data_formats/yolo/base.py
  src/datumaro/plugins/specs.json
  tests/assets/roboflow_dataset/coco/train/_annotations.coco.json
  tests/assets/roboflow_dataset/coco/train/train_001.jpg
  tests/assets/roboflow_dataset/coco/train/train_002.jpg
  tests/assets/roboflow_dataset/coco/val/_annotations.coco.json
  tests/assets/roboflow_dataset/coco/val/val_001.jpg
  tests/assets/roboflow_dataset/createml/train/_annotations.createml.json
  tests/assets/roboflow_dataset/createml/train/train_001.jpg
  tests/assets/roboflow_dataset/createml/train/train_002.jpg
  tests/assets/roboflow_dataset/createml/val/_annotations.createml.json
  tests/assets/roboflow_dataset/createml/val/val_001.jpg
  tests/assets/roboflow_dataset/multiclass/train/_classes.csv
  tests/assets/roboflow_dataset/multiclass/train/train_001.jpg
  tests/assets/roboflow_dataset/multiclass/train/train_002.jpg
  tests/assets/roboflow_dataset/multiclass/val/_classes.csv
  tests/assets/roboflow_dataset/multiclass/val/val_001.jpg
  tests/assets/roboflow_dataset/voc/train/train_001.jpg
  tests/assets/roboflow_dataset/voc/train/train_001.xml
  tests/assets/roboflow_dataset/voc/train/train_002.jpg
  tests/assets/roboflow_dataset/voc/train/train_002.xml
  tests/assets/roboflow_dataset/voc/val/val_001.jpg
  tests/assets/roboflow_dataset/voc/val/val_001.xml
  tests/assets/roboflow_dataset/yolo/data.yaml
  tests/assets/roboflow_dataset/yolo/train/images/train_001.jpg
  tests/assets/roboflow_dataset/yolo/train/images/train_002.jpg
  tests/assets/roboflow_dataset/yolo/train/labels/train_001.txt
  tests/assets/roboflow_dataset/yolo/train/labels/train_002.txt
  tests/assets/roboflow_dataset/yolo/val/images/val_001.jpg
  tests/assets/roboflow_dataset/yolo/val/labels/val_001.txt
  tests/assets/roboflow_dataset/yolo_obb/data.yaml
  tests/assets/roboflow_dataset/yolo_obb/train/images/train_001.jpg
  tests/assets/roboflow_dataset/yolo_obb/train/images/train_002.jpg
  tests/assets/roboflow_dataset/yolo_obb/train/labelTxt/train_001.txt
  tests/assets/roboflow_dataset/yolo_obb/train/labelTxt/train_002.txt
  tests/assets/roboflow_dataset/yolo_obb/val/images/val_001.jpg
  tests/assets/roboflow_dataset/yolo_obb/val/labelTxt/val_001.txt
  tests/integration/cli/test_merge.py
  tests/integration/cli/test_yolo_format.py
  tests/unit/data_formats/coco/test_roboflow.py
  tests/unit/data_formats/test_roboflow.py
  tests/unit/data_formats/test_yolo_format.py
  tests/unit/test_yolo_format.py
Labels: data formats, FEATURE

#1049 Add MissingAnnotationDetection transform
  CHANGELOG.md
  src/datumaro/components/annotations/matcher.py
  src/datumaro/components/launcher.py
  src/datumaro/plugins/missing_annotation_detection.py
  src/datumaro/plugins/specs.json
  tests/unit/test_missing_annotation_detection.py
Labels: FEATURE

#1056 Add OVMSLauncher
  CHANGELOG.md
  requirements-core.txt
  src/datumaro/plugins/ovms_plugin/__init__.py
  src/datumaro/plugins/ovms_plugin/launcher.py
  src/datumaro/plugins/ovms_plugin/samples/__init__.py
  src/datumaro/plugins/ovms_plugin/samples/face_detection.py
  src/datumaro/plugins/specs.json
  tests/unit/launchers/__init__.py
  tests/unit/launchers/test_openvino_launcher.py
  tests/unit/launchers/test_ovms_launcher.py
Labels: FEATURE

#1068 Update publish workflow
  .github/workflows/publish_sdist_to_pypi.yml
  pyproject.toml
Labels: CI

#1066 Add tabulate to requirements-core.txt
  requirements-core.txt
Labels: BUG

#1060 Add CVAT data format document
  CHANGELOG.md
  docs/source/docs/data-formats/formats/cvat.md
Labels: DOC

#1063 Add Jupyter notebook example for the missing annotation detection feature
  CHANGELOG.md
  docs/source/docs/jupyter_notebook_examples/e2e_example.rst
  notebooks/16_missing_annotation_detection.ipynb
Labels: DOC
