Repository openvinotoolkit/datumaro, pull requests merged in 2023-09, with the labels that each got.

#1141 Mark xfails on flaky and unavailable tests
  tests/integration/cli/test_generator.py
  tests/integration/cli/test_utils.py
  tests/unit/test_fractal_image_generator.py
Labels: BUG

#1140 Remove deprecates announced to be removed in 1.5.0
  CHANGELOG.md
  src/datumaro/__init__.py
  src/datumaro/cli/commands/convert.py
  src/datumaro/cli/commands/patch.py
  src/datumaro/cli/commands/require_project/modification/export.py
  src/datumaro/components/dataset_base.py
  src/datumaro/components/exporter.py
  src/datumaro/components/media.py
  src/datumaro/components/merge/base.py
  src/datumaro/plugins/data_formats/arrow/exporter.py
  src/datumaro/plugins/data_formats/datumaro_binary/exporter.py
  src/datumaro/plugins/data_formats/tf_detection_api/exporter.py
  src/datumaro/util/image.py
  tests/integration/cli/test_kitti_raw_format.py
  tests/integration/cli/test_patch.py
  tests/integration/cli/test_project.py
  tests/integration/cli/test_sly_point_cloud_format.py
  tests/integration/cli/test_video.py
  tests/integration/cli/test_voc_format.py
  tests/integration/cli/test_yolo_format.py
  tests/unit/data_formats/test_yolo_strict_format.py
  tests/unit/test_images.py
  tests/utils/test_utils.py
Labels: ENHANCE

#1138 Raise VcsAlreadyExists error if vcs directory exists
  CHANGELOG.md
  src/datumaro/components/errors.py
  src/datumaro/components/project.py
  tests/unit/test_project.py
Labels: BUG

#1134 Add notebook example for SAMBboxToInstanceMask transform
  CHANGELOG.md
  docker/segment-anything/Dockerfile.exporter
  docker/segment-anything/Dockerfile.ovms
  docker/segment-anything/Dockerfile.triton
  docker/segment-anything/scripts/export_onnx_encoder.py
  docs/source/docs/jupyter_notebook_examples/transform.rst
  notebooks/18_bbox_to_instance_mask_using_sam.ipynb
  src/datumaro/plugins/inference_server_plugin/__init__.py
  src/datumaro/plugins/sam_transforms/bbox_to_inst_mask.py
Labels: DOC, FEATURE

#1145 Add multi-threading option to ModelTransform and SAMBboxToInstanceMask
  CHANGELOG.md
  notebooks/18_bbox_to_instance_mask_using_sam.ipynb
  src/datumaro/components/dataset.py
  src/datumaro/components/hl_ops/__init__.py
  src/datumaro/components/transformer.py
  src/datumaro/plugins/missing_annotation_detection.py
  src/datumaro/plugins/sam_transforms/bbox_to_inst_mask.py
  src/datumaro/util/multi_procs_util.py
  tests/unit/components/test_transformer.py
  tests/unit/test_util.py
  tests/unit/transforms/test_sam_transforms.py
Labels: ENHANCE

#1149 Fix flaky test by setting the join timeout to infinite
  src/datumaro/util/multi_procs_util.py
  tests/unit/test_util.py
Labels: BUG

#1153 Enhance Datumaro data format stream importer performance
  CHANGELOG.md
  rust/Cargo.toml
  rust/src/coco_page_mapper.rs
  rust/src/datum_page_mapper.rs
  rust/src/lib.rs
  rust/src/page_mapper.rs
  rust/src/page_maps.rs
  rust/src/test_helpers.rs
  rust/src/utils.rs
  src/datumaro/plugins/data_formats/datumaro/base.py
  src/datumaro/plugins/data_formats/datumaro/page_mapper.py
  tests/conftest.py
  tests/utils/test_utils.py
Labels: ENHANCE

#1158 Modify coco to export annotations without media
  CHANGELOG.md
  src/datumaro/plugins/data_formats/coco/exporter.py
  tests/unit/test_coco_format.py
Labels: BUG, data formats
