Repository openvinotoolkit/datumaro, pull requests merged in 2023-01, with the labels that each got.

#782 Install our package first before building docs
  .github/workflows/github_pages.yml
Labels: bug, infra, ready-to-review

#789 Fix MacOS CI failures
  .github/workflows/pr_checks.yml
  .gitignore
  CHANGELOG.md
  datumaro/plugins/synthetic_data/utils.py
Labels: bug, infra, ready-to-review

#790 Add Tile transformation
  3rd-party.txt
  CHANGELOG.md
  datumaro/components/annotation.py
  datumaro/components/media.py
  datumaro/plugins/tiling/__init__.py
  datumaro/plugins/tiling/tile.py
  datumaro/plugins/tiling/untile.py
  datumaro/plugins/tiling/util.py
  requirements-core.txt
  tests/test_images.py
  tests/test_tiling.py
Labels: enhancement

#791 Add video keyframe extraction
  CHANGELOG.md
  datumaro/plugins/data_formats/video.py
  tests/assets/video_dataset/video.avi
  tests/cli/test_video.py
Labels: enhancement

#794 Add TileTransform documentation and Jupyter notebook example
  CHANGELOG.md
  datumaro/components/media.py
  datumaro/plugins/tiling/__init__.py
  datumaro/plugins/tiling/tile.py
  notebooks/06_tiling.ipynb
  site/content/en/docs/python-api/_index.md
  site/content/en/docs/python-api/python-api-examples/tiling.md
  site/source/api/plugins/plugins/datumaro.plugins.tiling.rst
  tests/test_tiling.py
Labels: bug, documentation

#796 Add MergeTileTransform
  3rd-party.txt
  CHANGELOG.md
  datumaro/components/annotation.py
  datumaro/components/media.py
  datumaro/plugins/tiling/merge_tile.py
  datumaro/plugins/tiling/untile.py
  notebooks/06_tiling.ipynb
  requirements-default.txt
  tests/test_tiling.py
Labels: enhancement
