Repository openvinotoolkit/datumaro, pull requests merged in 2023-04, with the labels that each got.

#907 Fix negated property
  CHANGELOG.md
  datumaro/components/media.py
Labels: BUG

#908 [Doc] Reorganize content structure
  docs/source/docs/data-formats/datumaro_format.md
  docs/source/docs/data-formats/index.rst
  docs/source/docs/data-formats/media_formats.md
  docs/source/docs/data-formats/supported_formats.md
  docs/source/docs/index.rst
  docs/source/docs/level-up/basic_skills/index.rst
  docs/source/docs/level-up/index.rst
  docs/source/docs/level-up/intermediate_skills/data_aggregation.md
  docs/source/docs/level-up/intermediate_skills/data_comparison.md
  docs/source/docs/level-up/intermediate_skills/data_exploration.md
  docs/source/docs/level-up/intermediate_skills/data_generation.md
  docs/source/docs/level-up/intermediate_skills/data_merge.md
  docs/source/docs/level-up/intermediate_skills/data_refinement.md
  docs/source/docs/level-up/intermediate_skills/index.rst
  docs/source/docs/user-manual/index.rst
  docs/source/docs/user-manual/model_preparation.md
Labels: DOC

#909 Refactor download CLI command
  CHANGELOG.md
  datumaro/cli/__main__.py
  datumaro/cli/commands/__init__.py
  datumaro/cli/commands/describe_downloads.py
  datumaro/cli/commands/download.py
  datumaro/cli/commands/no_project/__init__.py
  datumaro/cli/commands/no_project/download.py
  datumaro/cli/util/__init__.py
  tests/conftest.py
  tests/integration/cli/test_describe_downloads.py
  tests/integration/cli/test_download.py
Labels: refactoring

#915 Fix unit test errors from tensorflow-datasets==4.9.0
  .github/workflows/nightly_check.yml
  .github/workflows/pr_check.yml
  .github/workflows/weekly_check.yml
  setup.py
  tests/requirements.txt
Labels: BUG

#910 Refactor CLI commands w/ and w/o project
  CHANGELOG.md
  datumaro/cli/__main__.py
  datumaro/cli/commands/__init__.py
  datumaro/cli/commands/add.py
  datumaro/cli/commands/convert.py
  datumaro/cli/commands/download.py
  datumaro/cli/commands/export.py
  datumaro/cli/commands/filter.py
  datumaro/cli/commands/import_.py
  datumaro/cli/commands/remove.py
  datumaro/cli/commands/require_project/__init__.py
  datumaro/cli/commands/require_project/dataset_operations/__init__.py
  datumaro/cli/commands/require_project/dataset_operations/diff.py
  datumaro/cli/commands/require_project/dataset_operations/export.py
  datumaro/cli/commands/require_project/dataset_operations/info.py
  datumaro/cli/commands/require_project/dataset_operations/stats.py
  datumaro/cli/commands/require_project/dataset_operations/transform.py
  datumaro/cli/commands/require_project/dataset_operations/validate.py
  datumaro/cli/commands/require_project/modification/__init__.py
  datumaro/cli/commands/require_project/modification/add.py
  datumaro/cli/commands/require_project/modification/create.py
  datumaro/cli/commands/require_project/modification/import_.py
  datumaro/cli/commands/require_project/modification/remove.py
  datumaro/cli/commands/require_project/versioning/__init__.py
  datumaro/cli/commands/require_project/versioning/checkout.py
  datumaro/cli/commands/require_project/versioning/commit.py
  datumaro/cli/commands/require_project/versioning/info.py
  datumaro/cli/commands/require_project/versioning/log.py
  datumaro/cli/commands/require_project/versioning/status.py
  datumaro/cli/commands/stats.py
  datumaro/cli/contexts/project/__init__.py
  datumaro/cli/contexts/source.py
  datumaro/cli/util/__init__.py
  datumaro/cli/util/diff.py
  datumaro/cli/util/project.py
  datumaro/util/telemetry_utils.py
  tests/integration/cli/test_diff.py
  tests/integration/cli/test_dm_binary_encryption.py
  tests/integration/cli/test_explain.py
  tests/integration/cli/test_image_zip_format.py
  tests/integration/cli/test_model.py
  tests/integration/cli/test_project.py
  tests/integration/cli/test_transform.py
  tests/integration/cli/test_video.py
  tests/integration/cli/test_voc_format.py
  tests/integration/cli/test_yolo_format.py
  tests/unit/test_telemetry_utils.py
Labels: refactoring

#914 Add tfds:uc_merced and tfds:eurosat download
  CHANGELOG.md
  datumaro/components/extractor_tfds.py
Labels: ENHANCE

#919 Fix log issue when importing celeba and align celeba dataset
  CHANGELOG.md
  datumaro/plugins/data_formats/celeba/celeba.py
Labels: BUG

#912 Refactor hl_ops.py
  CHANGELOG.md
  datumaro/__init__.py
  datumaro/components/hl_ops.py
  datumaro/components/hl_ops/__init__.py
  tests/unit/test_dataset.py
  tests/unit/test_hl_ops.py
Labels: refactoring

#918 Fix not saving extra images of PointCloud in datumaro format
  CHANGELOG.md
  datumaro/plugins/data_formats/datumaro/exporter.py
Labels: BUG

#923 Infra/fix health check
  .github/workflows/health_check.yml
  .github/workflows/issue_assignment.yml
  .github/workflows/pypi_publish.yml
Labels: CI

#905 Fix for #903
  .github/workflows/code_scan.yml
  .github/workflows/nightly_check.yml
  .github/workflows/notify_teams.yml
  .github/workflows/weekly_check.yml
Labels: CI

#920 [Doc] add tutorials for level 3 and 4
  docs/source/docs/level-up/basic_skills/03_dataset_import_export.md
  docs/source/docs/level-up/basic_skills/03_dataset_import_export.rst
  docs/source/docs/level-up/basic_skills/04_detect_data_format.md
  docs/source/docs/level-up/basic_skills/04_detect_data_format.rst
  docs/source/docs/level-up/basic_skills/index.rst
Labels: DOC

#927 Add off the shelf progress reporters
  datumaro/__init__.py
  datumaro/components/progress_reporting.py
Labels: ENHANCE, user experience

#931 Add Apache Arrow format support
  CHANGELOG.md
  datumaro/components/annotation.py
  datumaro/components/dataset.py
  datumaro/components/exporter.py
  datumaro/components/media.py
  datumaro/components/progress_reporting.py
  datumaro/plugins/data_formats/arrow/__init__.py
  datumaro/plugins/data_formats/arrow/arrow_dataset.py
  datumaro/plugins/data_formats/arrow/base.py
  datumaro/plugins/data_formats/arrow/exporter.py
  datumaro/plugins/data_formats/arrow/format.py
  datumaro/plugins/data_formats/arrow/importer.py
  datumaro/plugins/data_formats/arrow/mapper/dataset_item.py
  datumaro/plugins/data_formats/arrow/mapper/media.py
  datumaro/plugins/data_formats/arrow/mapper/utils.py
  datumaro/plugins/transforms.py
  datumaro/util/file_utils.py
  datumaro/util/image.py
  requirements-core.txt
  tests/unit/data_formats/arrow/__init__.py
  tests/unit/data_formats/arrow/conftest.py
  tests/unit/data_formats/arrow/test_arrow_format.py
  tests/unit/test_transforms.py
  tests/utils/test_utils.py
Labels: FEATURE

#938 Fix regex for release candidates
  .github/workflows/publish_sdist_to_pypi.yml
Labels: BUG, CI

#939 Fix arrow format patch error on python 3.7
  datumaro/plugins/data_formats/arrow/exporter.py
Labels: BUG

#934 Add unit test for ArrowDataset
  datumaro/components/progress_reporting.py
  datumaro/plugins/data_formats/arrow/arrow_dataset.py
  tests/unit/data_formats/arrow/conftest.py
  tests/unit/data_formats/arrow/test_arrow_format.py
Labels: TEST

#930 Update merge tutorial for real life usecase
  notebooks/01_merge_multiple_datasets_for_classification.ipynb
Labels: DOC

#932 Refactor merge cli command
  datumaro/cli/commands/merge.py
  datumaro/components/hl_ops/__init__.py
  datumaro/components/merge/__init__.py
  datumaro/components/merge/base.py
  datumaro/components/merge/exact_merge.py
  datumaro/components/merge/intersect_merge.py
  datumaro/components/merge/union_merge.py
  tests/integration/cli/test_merge.py
  tests/unit/test_ops.py
Labels: ENHANCE, refactoring

#935 Update basic skills - 02_dataset_download
  docs/requirements.txt
  docs/source/conf.py
  docs/source/docs/level-up/advanced_skills/index.rst
  docs/source/docs/level-up/basic_skills/02_dataset_download.md
  docs/source/docs/level-up/basic_skills/02_dataset_download.rst
  docs/source/docs/level-up/basic_skills/03_dataset_import_export.rst
  docs/source/docs/level-up/basic_skills/04_detect_data_format.rst
  docs/source/docs/level-up/basic_skills/index.rst
  docs/source/docs/level-up/intermediate_skills/08_data_validate.rst
  docs/source/docs/level-up/intermediate_skills/index.rst
Labels: DOC

#944 Refactor Image/PointCloud 2
  CHANGELOG.md
  datumaro/cli/commands/search.py
  datumaro/components/dataset_base.py
  datumaro/components/dataset_item_storage.py
  datumaro/components/merge/exact_merge.py
  datumaro/components/operations.py
  datumaro/plugins/data_formats/datumaro/exporter.py
  datumaro/plugins/data_formats/kitti_raw/exporter.py
  datumaro/plugins/data_formats/mapillary_vistas/base.py
  datumaro/plugins/data_formats/sly_pointcloud/exporter.py
  datumaro/plugins/data_formats/yolo/base.py
  datumaro/plugins/sampler/relevancy_sampler.py
  datumaro/plugins/transforms.py
  tests/unit/operations/test_statistics.py
  tests/unit/test_kitti_raw_format.py
  tests/unit/test_ops.py
  tests/unit/test_sly_pointcloud_format.py
  tests/unit/test_transforms.py
Labels: BUG, refactoring

#945 Add basic skills - 01_project_manipulation
  docs/requirements.txt
  docs/source/conf.py
  docs/source/docs/level-up/advanced_skills/11_project_versioning.md
  docs/source/docs/level-up/advanced_skills/11_project_versioning.rst
  docs/source/docs/level-up/basic_skills/01_project_manipulation.md
  docs/source/docs/level-up/basic_skills/01_project_manipulation.rst
Labels: DOC

#951 Abbreviate "detect-format" to "detect" for prettifying
  datumaro/cli/commands/__init__.py
  docs/source/docs/command-reference/detect.md
  docs/source/docs/command-reference/index.rst
  docs/source/docs/level-up/basic_skills/04_detect_data_format.rst
  tests/integration/cli/test_detect_format.py
Labels: cli, refactoring

#948 Add Arrow format doc
  CHANGELOG.md
  docs/source/docs/explanation/formats/arrow.md
  docs/source/docs/explanation/formats/images/arrow/annotations.png
  docs/source/docs/explanation/formats/images/arrow/attributes.png
  docs/source/docs/explanation/formats/images/arrow/caption.png
  docs/source/docs/explanation/formats/images/arrow/cuboid3d.png
  docs/source/docs/explanation/formats/images/arrow/image_attributes.png
  docs/source/docs/explanation/formats/images/arrow/label.png
  docs/source/docs/explanation/formats/images/arrow/mask.png
  docs/source/docs/explanation/formats/images/arrow/point.png
  docs/source/docs/explanation/formats/images/arrow/pointcloud_attributes.png
  docs/source/docs/explanation/formats/images/arrow/shape.png
Labels: DOC

#953 Add basic skills - Level 10: Data Generation
  docs/source/docs/level-up/intermediate_skills/10_data_generation.md
  docs/source/docs/level-up/intermediate_skills/10_data_generation.rst
Labels: DOC

#949 Add basic skills - Level 11: Project Versioning
  datumaro/cli/__main__.py
  docs/source/docs/level-up/advanced_skills/11_project_versioning.rst
Labels: DOC

#952 Move project free commands to outside again
  datumaro/cli/commands/__init__.py
  datumaro/cli/commands/diff.py
  datumaro/cli/commands/info.py
  datumaro/cli/commands/require_project/__init__.py
  datumaro/cli/commands/require_project/dataset_operations/__init__.py
  datumaro/cli/commands/require_project/modification/__init__.py
  datumaro/cli/commands/require_project/modification/export.py
  datumaro/cli/commands/stats.py
  datumaro/cli/commands/transform.py
  datumaro/cli/commands/validate.py
  datumaro/util/telemetry_utils.py
  tests/integration/cli/test_diff.py
  tests/integration/cli/test_project.py
  tests/integration/cli/test_transform.py
  tests/integration/cli/test_voc_format.py
  tests/integration/cli/test_yolo_format.py
  tests/unit/test_telemetry_utils.py
Labels: cli, refactoring

#954 Align docs with the recent CLI changes
  .github/workflows/docs_latest.yml
  .github/workflows/docs_stable.yml
  datumaro/cli/__main__.py
  docs/README.md
  docs/source/conf.py
  docs/source/docs/command-reference/context/checkout.md
  docs/source/docs/command-reference/context/commit.md
  docs/source/docs/command-reference/context/create.md
  docs/source/docs/command-reference/context/export.md
  docs/source/docs/command-reference/context/index.rst
  docs/source/docs/command-reference/context/log.md
  docs/source/docs/command-reference/context/models.md
  docs/source/docs/command-reference/context/projects.md
  docs/source/docs/command-reference/context/sources.md
  docs/source/docs/command-reference/context/status.md
  docs/source/docs/command-reference/context/util.md
  docs/source/docs/command-reference/context_free/convert.md
  docs/source/docs/command-reference/context_free/detect.md
  docs/source/docs/command-reference/context_free/diff.md
  docs/source/docs/command-reference/context_free/dinfo.md
  docs/source/docs/command-reference/context_free/download.md
  docs/source/docs/command-reference/context_free/explain.md
  docs/source/docs/command-reference/context_free/filter.md
  docs/source/docs/command-reference/context_free/generate.md
  docs/source/docs/command-reference/context_free/index.rst
  docs/source/docs/command-reference/context_free/merge.md
  docs/source/docs/command-reference/context_free/patch.md
  docs/source/docs/command-reference/context_free/searcher.md
  docs/source/docs/command-reference/context_free/stats.md
  docs/source/docs/command-reference/context_free/transform.md
  docs/source/docs/command-reference/context_free/validate.md
  docs/source/docs/command-reference/describe-downloads.md
  docs/source/docs/command-reference/download.md
  docs/source/docs/command-reference/overview.rst
  docs/source/docs/data-formats/media_formats.md
  docs/source/docs/explanation/architecture.rst
  docs/source/docs/explanation/command_line.dot
  docs/source/docs/explanation/formats/icdar.md
  docs/source/docs/explanation/formats/imagenet.md
  docs/source/docs/explanation/formats/lfw.md
  docs/source/docs/explanation/formats/market1501.md
  docs/source/docs/explanation/formats/vgg_face2.md
  docs/source/docs/index.rst
  docs/source/docs/level-up/advanced_skills/11_project_versioning.rst
  docs/source/docs/level-up/intermediate_skills/08_data_validate.rst
  docs/source/docs/user-manual/how_to_use_datumaro.md
Labels: DOC

#955 Revisit Juypter notebook examples
  docs/source/docs/index.rst
  docs/source/docs/jupyter_notebook_examples/dataset_handler.rst
  docs/source/docs/jupyter_notebook_examples/e2e_example.rst
  docs/source/docs/jupyter_notebook_examples/explore.rst
  docs/source/docs/jupyter_notebook_examples/filter.rst
  docs/source/docs/jupyter_notebook_examples/notebooks
  docs/source/docs/jupyter_notebook_examples/transform.rst
  docs/source/docs/jupyter_notebook_examples/visualizer.rst
  docs/source/docs/level-up/intermediate_skills/09_data_exploration.rst
  docs/source/docs/reference/jupyter_notebook_examples/dataset_handler.rst
  docs/source/docs/reference/jupyter_notebook_examples/e2e_example.rst
  docs/source/docs/reference/jupyter_notebook_examples/encrypt_dataset.rst
  docs/source/docs/reference/jupyter_notebook_examples/explore.rst
  docs/source/docs/reference/jupyter_notebook_examples/index.rst
  docs/source/docs/reference/jupyter_notebook_examples/notebooks
  docs/source/docs/reference/jupyter_notebook_examples/tiling.rst
  docs/source/docs/reference/jupyter_notebook_examples/transform.rst
  notebooks/08_e2e_example_yolo_ultralytics_trainer.ipynb
  notebooks/09_encrypt_dataset.ipynb
Labels: DOC

#957 Update 3rd party txt
  3rd-party.txt
Labels: CI

#961 Fix docs in `data_formats` section
  docs/source/docs/data-formats/datumaro_format.md
  docs/source/docs/data-formats/media_formats.md
  docs/source/docs/data-formats/supported_formats.md
Labels: DOC

#962 Fix Misc section's weird nesting structure and broken links
  docs/source/docs/explanation/architecture.rst
  docs/source/docs/explanation/formats/cifar.md
  docs/source/docs/explanation/formats/cityscapes.md
  docs/source/docs/explanation/formats/coco.md
  docs/source/docs/explanation/formats/kitti.md
  docs/source/docs/explanation/formats/mnist.md
  docs/source/docs/explanation/formats/open_images.md
  docs/source/docs/explanation/formats/pascal_voc.md
  docs/source/docs/explanation/plugins/openvino_plugin.md
  docs/source/docs/index.rst
  docs/source/docs/user-manual/extending.md
  docs/source/docs/user-manual/index.rst
  notebooks/10_noisy_label_detection.ipynb
Labels: DOC

#964 Find and replace for the recent CLI changes
  datumaro/components/project.py
  docs/source/docs/command-reference/context_free/explain.md
  docs/source/docs/explanation/formats/ade20k2017.md
  docs/source/docs/explanation/formats/ade20k2020.md
  docs/source/docs/explanation/formats/align_celeba.md
  docs/source/docs/explanation/formats/arrow.md
  docs/source/docs/explanation/formats/ava_action.md
  docs/source/docs/explanation/formats/brats.md
  docs/source/docs/explanation/formats/brats_numpy.md
  docs/source/docs/explanation/formats/celeba.md
  docs/source/docs/explanation/formats/cifar.md
  docs/source/docs/explanation/formats/cityscapes.md
  docs/source/docs/explanation/formats/coco.md
  docs/source/docs/explanation/formats/common_semantic_segmentation.md
  docs/source/docs/explanation/formats/common_super_resolution.md
  docs/source/docs/explanation/formats/datumaro.md
  docs/source/docs/explanation/formats/datumaro_binary.md
  docs/source/docs/explanation/formats/icdar.md
  docs/source/docs/explanation/formats/image_zip.md
  docs/source/docs/explanation/formats/imagenet.md
  docs/source/docs/explanation/formats/kinetics.md
  docs/source/docs/explanation/formats/kitti.md
  docs/source/docs/explanation/formats/kitti_raw.md
  docs/source/docs/explanation/formats/lfw.md
  docs/source/docs/explanation/formats/mapillary_vistas.md
  docs/source/docs/explanation/formats/market1501.md
  docs/source/docs/explanation/formats/mars.md
  docs/source/docs/explanation/formats/mnist.md
  docs/source/docs/explanation/formats/mpii.md
  docs/source/docs/explanation/formats/mpii_json.md
  docs/source/docs/explanation/formats/mvtec.md
  docs/source/docs/explanation/formats/nyu_depth_v2.md
  docs/source/docs/explanation/formats/open_images.md
  docs/source/docs/explanation/formats/pascal_voc.md
  docs/source/docs/explanation/formats/sly_pointcloud.md
  docs/source/docs/explanation/formats/synthia.md
  docs/source/docs/explanation/formats/vgg_face2.md
  docs/source/docs/explanation/formats/video.md
  docs/source/docs/explanation/formats/vott_csv.md
  docs/source/docs/explanation/formats/vott_json.md
  docs/source/docs/explanation/formats/wider_face.md
  docs/source/docs/explanation/formats/yolo.md
  docs/source/docs/explanation/formats/yolo_ultralytics.md
Labels: DOC

#965 Fix links in Explanation-Formats
  docs/source/docs/explanation/formats/ade20k2017.md
  docs/source/docs/explanation/formats/ade20k2020.md
  docs/source/docs/explanation/formats/align_celeba.md
  docs/source/docs/explanation/formats/brats.md
  docs/source/docs/explanation/formats/brats_numpy.md
  docs/source/docs/explanation/formats/celeba.md
  docs/source/docs/explanation/formats/cifar.md
  docs/source/docs/explanation/formats/common_semantic_segmentation.md
  docs/source/docs/explanation/formats/common_super_resolution.md
  docs/source/docs/explanation/formats/mpii.md
  docs/source/docs/explanation/formats/mpii_json.md
  docs/source/docs/explanation/formats/nyu_depth_v2.md
  docs/source/docs/explanation/formats/synthia.md
  docs/source/docs/explanation/formats/vott_csv.md
  docs/source/docs/explanation/formats/vott_json.md
Labels: DOC

#969 Fix docs context-free commands subsection
  docs/source/docs/command-reference/context_free/convert.md
  docs/source/docs/command-reference/context_free/detect.md
  docs/source/docs/command-reference/context_free/diff.md
  docs/source/docs/command-reference/context_free/dinfo.md
  docs/source/docs/command-reference/context_free/download.md
  docs/source/docs/command-reference/context_free/explain.md
  docs/source/docs/command-reference/context_free/explorer.md
  docs/source/docs/command-reference/context_free/filter.md
  docs/source/docs/command-reference/context_free/generate.md
  docs/source/docs/command-reference/context_free/merge.md
  docs/source/docs/command-reference/context_free/patch.md
  docs/source/docs/command-reference/context_free/stats.md
  docs/source/docs/command-reference/context_free/transform.md
  docs/source/docs/command-reference/context_free/validate.md
Labels: DOC

#975 fix typo - level 10 data generation
  docs/source/docs/level-up/intermediate_skills/10_data_generation.rst
Labels: DOC

#974 Warn coco format users
  datumaro/plugins/data_formats/coco/base.py
  tests/unit/test_coco_format.py
Labels: user experience

#976 Add CocoRoboflowImporter
  CHANGELOG.md
  datumaro/plugins/data_formats/coco/base.py
  datumaro/plugins/data_formats/coco/format.py
  datumaro/plugins/data_formats/coco/importer.py
  tests/assets/coco_dataset/coco_roboflow/train/_annotations.coco.json
  tests/assets/coco_dataset/coco_roboflow/train/a.jpg
  tests/assets/coco_dataset/coco_roboflow/val/_annotations.coco.json
  tests/assets/coco_dataset/coco_roboflow/val/b.jpg
  tests/unit/data_formats/base.py
  tests/unit/data_formats/coco/__init__.py
  tests/unit/data_formats/coco/test_roboflow.py
  tests/unit/data_formats/test_common_semantic_segmentation_format.py
Labels: data formats, FEATURE

#978 Fix bytes property bug
  CHANGELOG.md
  datumaro/components/media.py
  tests/unit/test_images.py
Labels: BUG
