Repository openvinotoolkit/datumaro, pull requests merged in 2023-07, with the labels that each got.

#1069 Enhance the error message for datum stats to be more user friendly
  CHANGELOG.md
  src/datumaro/cli/commands/stats.py
Labels: ENHANCE

#1072 Migrate dvc >= 3.0.0
  CHANGELOG.md
  requirements-default.txt
  src/datumaro/components/project.py
Labels: ENHANCE

#1058 Add Prune API
  CHANGELOG.md
  requirements-core.txt
  src/datumaro/cli/commands/__init__.py
  src/datumaro/cli/commands/explore.py
  src/datumaro/cli/commands/prune.py
  src/datumaro/components/algorithms/hash_key_inference/__init__.py
  src/datumaro/components/algorithms/hash_key_inference/base.py
  src/datumaro/components/algorithms/hash_key_inference/explorer.py
  src/datumaro/components/algorithms/hash_key_inference/hashkey_util.py
  src/datumaro/components/algorithms/hash_key_inference/prune.py
  tests/integration/cli/test_prune.py
  tests/unit/test_explorer.py
  tests/unit/test_prune.py
Labels: FEATURE

#1061 Reduce peak memory consumption during Datumaro and COCO extractors
  CHANGELOG.md
  src/datumaro/plugins/data_formats/coco/base.py
  src/datumaro/plugins/data_formats/datumaro/base.py
  tests/unit/data_formats/datumaro/test_datumaro_format.py
Labels: ENHANCE

#1076 Update index.rst
  docs/source/docs/data-formats/formats/index.rst
Labels: DOC

#1071 Add --encryption-key arg to datum convert command
  src/datumaro/cli/commands/convert.py
Labels: ENHANCE

#1075 Update issue_assignment.yml
  .github/workflows/issue_assignment.yml
Labels: CI

#1073 Refactor dataset.py to seperate DatasetStorage
  CHANGELOG.md
  src/datumaro/__init__.py
  src/datumaro/components/dataset.py
  src/datumaro/components/dataset_item_storage.py
  src/datumaro/components/dataset_storage.py
  src/datumaro/plugins/data_formats/camvid.py
  src/datumaro/plugins/data_formats/cifar.py
  src/datumaro/plugins/data_formats/cityscapes.py
  src/datumaro/plugins/data_formats/coco/exporter.py
  src/datumaro/plugins/data_formats/cvat/exporter.py
  src/datumaro/plugins/data_formats/datumaro/exporter.py
  src/datumaro/plugins/data_formats/kitti_raw/exporter.py
  src/datumaro/plugins/data_formats/open_images.py
  src/datumaro/plugins/data_formats/sly_pointcloud/exporter.py
  src/datumaro/plugins/data_formats/voc/exporter.py
  src/datumaro/plugins/data_formats/yolo/exporter.py
  tests/unit/test_dataset.py
Labels: refactoring

#1078 Support mask annotations for CVAT data format
  CHANGELOG.md
  docs/source/docs/data-formats/formats/cvat.md
  src/datumaro/plugins/data_formats/cvat/base.py
  src/datumaro/plugins/data_formats/cvat/exporter.py
  src/datumaro/plugins/data_formats/cvat/format.py
  src/datumaro/util/mask_tools.py
  tests/unit/test_cvat_format.py
Labels: ENHANCE, FEATURE

#1077 Implement StreamDatasetStorage and StreamDataset
  CHANGELOG.md
  src/datumaro/components/dataset.py
  src/datumaro/components/dataset_base.py
  src/datumaro/components/dataset_storage.py
  src/datumaro/components/errors.py
  tests/unit/components/__init__.py
  tests/unit/components/conftest.py
  tests/unit/components/test_dataset_storage.py
Labels: FEATURE

#1083 updated supported python version range
  .github/workflows/health_check.yml
  .github/workflows/nightly_check.yml
  CHANGELOG.md
  contributing.md
  docs/source/docs/get-started/quick-start-guide/installation.rst
  pyproject.toml
  setup.py
  tox.ini
Labels: ENHANCE, CI

#1085 Give notice that the deprecation works will be done in datumaro==1.5.0
  CHANGELOG.md
  src/datumaro/__init__.py
  src/datumaro/components/dataset.py
  src/datumaro/components/dataset_base.py
  src/datumaro/components/exporter.py
  src/datumaro/components/media.py
  src/datumaro/util/image.py
  tests/utils/test_utils.py
Labels: ENHANCE

#1088 Hotfix: Create Datumaro cache dir
  src/datumaro/cli/commands/generate.py
  src/datumaro/plugins/openvino_plugin/launcher.py
  src/datumaro/plugins/synthetic_data/image_generator.py
  src/datumaro/util/definitions.py
  tests/unit/test_util.py
Labels: ENHANCE

#1070 Add documentation and notebook example for Prune API
  CHANGELOG.md
  docs/images/centroid.png
  docs/images/cluster_random.png
  docs/images/entropy.png
  docs/images/query_clust.png
  docs/source/docs/command-reference/context_free/prune.md
  docs/source/docs/jupyter_notebook_examples/refine.rst
  docs/source/docs/level-up/advanced_skills/14_data_pruning.rst
  docs/source/docs/level-up/advanced_skills/index.rst
  notebooks/17_data_pruning.ipynb
  src/datumaro/components/algorithms/hash_key_inference/prune.py
Labels: DOC

#1082 Enable stream import for Datumaro data format
  CHANGELOG.md
  requirements-core.txt
  src/datumaro/components/dataset.py
  src/datumaro/plugins/data_formats/arrow/base.py
  src/datumaro/plugins/data_formats/datumaro/base.py
  src/datumaro/plugins/data_formats/datumaro/exporter.py
  src/datumaro/plugins/data_formats/datumaro/importer.py
  src/datumaro/plugins/data_formats/datumaro_binary/base.py
  tests/unit/data_formats/datumaro/conftest.py
  tests/unit/data_formats/datumaro/test_datumaro_binary_format.py
  tests/unit/data_formats/datumaro/test_datumaro_format.py
  tests/utils/test_utils.py
Labels: FEATURE

#1091 Enable stream import for COCO data format
  CHANGELOG.md
  src/datumaro/plugins/data_formats/coco/base.py
  src/datumaro/plugins/data_formats/coco/importer.py
  src/datumaro/plugins/data_formats/coco/page_mapper.py
  src/datumaro/plugins/data_formats/datumaro/base.py
  src/datumaro/plugins/data_formats/roboflow/base.py
  src/datumaro/plugins/data_formats/roboflow/importer.py
  src/datumaro/util/__init__.py
  tests/unit/data_formats/coco/test_roboflow.py
  tests/unit/test_coco_format.py
Labels: FEATURE

#1086 Fix UnionMerge
  CHANGELOG.md
  src/datumaro/components/merge/union_merge.py
  tests/integration/cli/test_merge.py
Labels: BUG

#1087 Support list query for explorer
  src/datumaro/components/algorithms/hash_key_inference/explorer.py
  tests/unit/test_explorer.py
Labels: ENHANCE

#1094 update contributing.md
  contributing.md
Labels: DOC

#1093 Fix misimplements for stream importer found while testing on the real-life COCO2017 object detection dataset
  CHANGELOG.md
  src/datumaro/components/contexts/__init__.py
  src/datumaro/components/contexts/importer.py
  src/datumaro/components/dataset.py
  src/datumaro/components/dataset_base.py
  src/datumaro/components/environment.py
  src/datumaro/components/importer.py
  src/datumaro/components/merge/base.py
  src/datumaro/components/merge/exact_merge.py
  src/datumaro/components/merge/extractor_merger.py
  src/datumaro/plugins/data_formats/coco/base.py
  src/datumaro/plugins/data_formats/coco/extractor_merger.py
  src/datumaro/plugins/data_formats/coco/importer.py
  src/datumaro/plugins/data_formats/coco/page_mapper.py
  src/datumaro/plugins/data_formats/datumaro/importer.py
  src/datumaro/plugins/data_formats/roboflow/importer.py
  src/datumaro/plugins/data_formats/voc/importer.py
  src/datumaro/plugins/data_formats/yolo/importer.py
  tests/unit/data_formats/base.py
  tests/unit/test_coco_format.py
  tests/utils/test_utils.py
Labels: BUG, FEATURE

#1098 Hotfix some mis-implements making datum stream importer slow
  CHANGELOG.md
  src/datumaro/components/progress_reporting.py
  src/datumaro/plugins/data_formats/datumaro/base.py
Labels: BUG, FEATURE

#1097 Documentatino for tabular format
  docs/source/docs/data-formats/formats/index.rst
  docs/source/docs/data-formats/formats/tabular.md
  docs/source/docs/data-formats/media_formats.md
  src/datumaro/components/annotation.py
  src/datumaro/components/media.py
  src/datumaro/plugins/data_formats/tabular.py
Labels: DOC

#1101 Fix: Dataset infos() can be broken if a transform not redefining infos() is stacked on the top
  CHANGELOG.md
  src/datumaro/components/transformer.py
  tests/unit/components/test_dataset_storage.py
  tests/unit/test_dataset.py
Labels: BUG, ENHANCE

#1102 Enable stream exporters: VOC, YOLO, Datumaro, and COCO data format
  CHANGELOG.md
  src/datumaro/components/dataset.py
  src/datumaro/components/dataset_storage.py
  src/datumaro/components/exporter.py
  src/datumaro/plugins/data_formats/arrow/exporter.py
  src/datumaro/plugins/data_formats/coco/exporter.py
  src/datumaro/plugins/data_formats/datumaro/exporter.py
  src/datumaro/plugins/data_formats/datumaro_binary/exporter.py
  src/datumaro/plugins/data_formats/voc/exporter.py
  src/datumaro/plugins/data_formats/yolo/exporter.py
  tests/unit/components/conftest.py
  tests/unit/components/test_dataset_storage.py
  tests/unit/data_formats/base.py
  tests/unit/data_formats/datumaro/test_datumaro_format.py
  tests/unit/data_formats/test_yolo_strict_format.py
  tests/unit/test_coco_format.py
  tests/utils/test_utils.py
Labels: FEATURE

#1109 Add utf-8 encoding directive
  setup.py
Labels: BUG

#1110 Report errors for COCO (stream) and Datumaro importers
  CHANGELOG.md
  src/datumaro/plugins/data_formats/coco/base.py
  src/datumaro/plugins/data_formats/datumaro/base.py
Labels: ENHANCE
