Repository openvinotoolkit/datumaro, pull requests merged in 2024-09, with the labels that each got.

#1607 Support multiple labels for kaggle format
  CHANGELOG.md
  src/datumaro/plugins/data_formats/kaggle/base.py
  tests/assets/kaggle_dataset/image_csv_multi_label/ann.csv
  tests/assets/kaggle_dataset/image_csv_multi_label/ann_wo_ext.csv
  tests/assets/kaggle_dataset/image_csv_multi_label/images/1.jpg
  tests/assets/kaggle_dataset/image_csv_multi_label/images/2.jpg
  tests/assets/kaggle_dataset/image_csv_multi_label/images/3.jpg
  tests/assets/kaggle_dataset/image_csv_multi_label/images/4.jpg
  tests/assets/kaggle_dataset/image_csv_multi_label/images/5.jpg
  tests/assets/kaggle_dataset/image_csv_multi_label/images/6.jpg
  tests/unit/data_formats/test_kaggle.py
Labels: ENHANCE

#1609 Fix merging of stream datasets
  .github/workflows/codeql.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/scorecard.yml
  CHANGELOG.md
  src/datumaro/components/dataset.py
  tests/unit/test_imagenet_format.py
Labels: BUG

#1613 Use DataFrame.map instead of DataFrame.applymap
  CHANGELOG.md
  src/datumaro/plugins/transforms.py
Labels: ENHANCE

#1594 Add PseudoLabeling transform for unlabeled dataset
  CHANGELOG.md
  docs/source/docs/command-reference/context_free/transform.md
  src/datumaro/plugins/specs.json
  src/datumaro/plugins/transforms.py
  tests/unit/test_transforms.py
Labels: FEATURE

#1621 Support subset for KITTI 3D format
  CHANGELOG.md
  src/datumaro/plugins/data_formats/kitti_3d/base.py
  src/datumaro/plugins/data_formats/kitti_3d/format.py
  src/datumaro/plugins/data_formats/kitti_3d/importer.py
  tests/assets/kitti_dataset/kitti_3d/calib/000001.txt
  tests/assets/kitti_dataset/kitti_3d/image_2/000001.png
  tests/assets/kitti_dataset/kitti_3d/label_2/000001.txt
  tests/assets/kitti_dataset/kitti_3d/training/velodyne/000001.bin
  tests/assets/kitti_dataset/kitti_3d/training/velodyne/000002.bin
  tests/assets/kitti_dataset/kitti_3d/training/velodyne/000003.bin
  tests/assets/kitti_dataset/kitti_3d_with_subset/calib/test/000002.txt
  tests/assets/kitti_dataset/kitti_3d_with_subset/calib/train/000000.txt
  tests/assets/kitti_dataset/kitti_3d_with_subset/calib/val/000001.txt
  tests/assets/kitti_dataset/kitti_3d_with_subset/image_2/test/000002.png
  tests/assets/kitti_dataset/kitti_3d_with_subset/image_2/train/000000.png
  tests/assets/kitti_dataset/kitti_3d_with_subset/image_2/val/000001.png
  tests/assets/kitti_dataset/kitti_3d_with_subset/label_2/test/000002.txt
  tests/assets/kitti_dataset/kitti_3d_with_subset/label_2/train/000000.txt
  tests/assets/kitti_dataset/kitti_3d_with_subset/label_2/val/000001.txt
  tests/unit/test_kitti_3d_format.py
Labels: ENHANCE
